blank_issues_enabled: false
issue_templates:
  - label: "Bug Report"
    description: File a bug report if something isn't working as expected.
    file: bug_report.md
  - label: "Feature Request"
    description: Suggest a new idea, enhancement, or improvement for diun-boost.
    file: feature_request.md
