blank_issues_enabled: false
issue_templates:
  - label: "\ud83d\udee0\ufe0f Bug Report"
    description: File a bug report if something isn't working as expected.
    file: bug_report.md
  - label: "\ud83c\udf1f Feature Request"
    description: Suggest a new idea, enhancement, or improvement for diun-boost.
    file: feature_request.md
